version: "3.8"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/project
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  webserver:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

  app:
    build: .
    command: bash -c "python manage.py migrate && uv run pytest -vv tests"
    volumes:
      - .:/project
    depends_on:
      - db
      - server
      - webserver
    environment:
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
