# Generated by Django 5.2.5 on 2025-09-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
